"""Tradeable universe for the signal engine.

NIFTY 100 = NIFTY 50 + NIFTY Next 50. Composition shifts ~quarterly;
yfinance silently skips tickers that have been delisted or renamed.

Each entry: (short_ticker, display_name, yfinance_ticker).
"""

# (ticker, company_name, yfinance_symbol)
NIFTY_100: list[tuple[str, str, str]] = [
    # --- NIFTY 50 ---
    ("RELIANCE", "Reliance Industries", "RELIANCE.NS"),
    ("TCS", "Tata Consultancy Services", "TCS.NS"),
    ("HDFCBANK", "HDFC Bank", "HDFCBANK.NS"),
    ("INFY", "Infosys", "INFY.NS"),
    ("ICICIBANK", "ICICI Bank", "ICICIBANK.NS"),
    ("HINDUNILVR", "Hindustan Unilever", "HINDUNILVR.NS"),
    ("BHARTIARTL", "Bharti Airtel", "BHARTIARTL.NS"),
    ("SBIN", "State Bank of India", "SBIN.NS"),
    ("BAJFINANCE", "Bajaj Finance", "BAJFINANCE.NS"),
    ("ITC", "ITC", "ITC.NS"),
    ("KOTAKBANK", "Kotak Mahindra Bank", "KOTAKBANK.NS"),
    ("LT", "Larsen & Toubro", "LT.NS"),
    ("AXISBANK", "Axis Bank", "AXISBANK.NS"),
    ("MARUTI", "Maruti Suzuki India", "MARUTI.NS"),
    ("ASIANPAINT", "Asian Paints", "ASIANPAINT.NS"),
    ("SUNPHARMA", "Sun Pharmaceutical", "SUNPHARMA.NS"),
    ("M&M", "Mahindra & Mahindra", "M&M.NS"),
    ("HCLTECH", "HCL Technologies", "HCLTECH.NS"),
    ("TITAN", "Titan Company", "TITAN.NS"),
    ("ULTRACEMCO", "UltraTech Cement", "ULTRACEMCO.NS"),
    ("WIPRO", "Wipro", "WIPRO.NS"),
    ("NTPC", "NTPC", "NTPC.NS"),
    ("ONGC", "Oil and Natural Gas Corp", "ONGC.NS"),
    ("POWERGRID", "Power Grid Corp", "POWERGRID.NS"),
    ("JSWSTEEL", "JSW Steel", "JSWSTEEL.NS"),
    ("NESTLEIND", "Nestle India", "NESTLEIND.NS"),
    ("TMPV", "Tata Motors Passenger Vehicles", "TMPV.NS"),
    ("TMCV", "Tata Motors Commercial Vehicles", "TMCV.NS"),
    ("BAJAJFINSV", "Bajaj Finserv", "BAJAJFINSV.NS"),
    ("ADANIENT", "Adani Enterprises", "ADANIENT.NS"),
    ("ADANIPORTS", "Adani Ports and SEZ", "ADANIPORTS.NS"),
    ("TATASTEEL", "Tata Steel", "TATASTEEL.NS"),
    ("COALINDIA", "Coal India", "COALINDIA.NS"),
    ("INDUSINDBK", "IndusInd Bank", "INDUSINDBK.NS"),
    ("GRASIM", "Grasim Industries", "GRASIM.NS"),
    ("BRITANNIA", "Britannia Industries", "BRITANNIA.NS"),
    ("EICHERMOT", "Eicher Motors", "EICHERMOT.NS"),
    ("HEROMOTOCO", "Hero MotoCorp", "HEROMOTOCO.NS"),
    ("HINDALCO", "Hindalco Industries", "HINDALCO.NS"),
    ("DRREDDY", "Dr. Reddy's Laboratories", "DRREDDY.NS"),
    ("CIPLA", "Cipla", "CIPLA.NS"),
    ("DIVISLAB", "Divi's Laboratories", "DIVISLAB.NS"),
    ("APOLLOHOSP", "Apollo Hospitals", "APOLLOHOSP.NS"),
    ("BAJAJ-AUTO", "Bajaj Auto", "BAJAJ-AUTO.NS"),
    ("BPCL", "Bharat Petroleum Corp", "BPCL.NS"),
    ("TECHM", "Tech Mahindra", "TECHM.NS"),
    ("SBILIFE", "SBI Life Insurance", "SBILIFE.NS"),
    ("HDFCLIFE", "HDFC Life Insurance", "HDFCLIFE.NS"),
    ("PERSISTENT", "Persistent Systems", "PERSISTENT.NS"),
    ("SHRIRAMFIN", "Shriram Finance", "SHRIRAMFIN.NS"),
    ("TATACONSUM", "Tata Consumer Products", "TATACONSUM.NS"),
    ("TRENT", "Trent", "TRENT.NS"),

    # --- NIFTY Next 50 (large/mid caps) ---
    ("AMBUJACEM", "Ambuja Cements", "AMBUJACEM.NS"),
    ("BANKBARODA", "Bank of Baroda", "BANKBARODA.NS"),
    ("BEL", "Bharat Electronics", "BEL.NS"),
    ("BERGEPAINT", "Berger Paints India", "BERGEPAINT.NS"),
    ("BOSCHLTD", "Bosch", "BOSCHLTD.NS"),
    ("CANBK", "Canara Bank", "CANBK.NS"),
    ("CHOLAFIN", "Cholamandalam Investment", "CHOLAFIN.NS"),
    ("COLPAL", "Colgate-Palmolive India", "COLPAL.NS"),
    ("DABUR", "Dabur India", "DABUR.NS"),
    ("DLF", "DLF", "DLF.NS"),
    ("DMART", "Avenue Supermarts (DMart)", "DMART.NS"),
    ("GAIL", "GAIL India", "GAIL.NS"),
    ("GODREJCP", "Godrej Consumer Products", "GODREJCP.NS"),
    ("HAL", "Hindustan Aeronautics", "HAL.NS"),
    ("HAVELLS", "Havells India", "HAVELLS.NS"),
    ("HINDPETRO", "Hindustan Petroleum", "HINDPETRO.NS"),
    ("ICICIGI", "ICICI Lombard General Insurance", "ICICIGI.NS"),
    ("ICICIPRULI", "ICICI Prudential Life Insurance", "ICICIPRULI.NS"),
    ("IOC", "Indian Oil Corp", "IOC.NS"),
    ("INDIGO", "InterGlobe Aviation (IndiGo)", "INDIGO.NS"),
    ("INDUSTOWER", "Indus Towers", "INDUSTOWER.NS"),
    ("IRCTC", "Indian Railway Catering & Tourism", "IRCTC.NS"),
    ("JINDALSTEL", "Jindal Steel & Power", "JINDALSTEL.NS"),
    ("LICI", "Life Insurance Corporation of India", "LICI.NS"),
    ("LUPIN", "Lupin", "LUPIN.NS"),
    ("MARICO", "Marico", "MARICO.NS"),
    ("MOTHERSON", "Samvardhana Motherson", "MOTHERSON.NS"),
    ("MUTHOOTFIN", "Muthoot Finance", "MUTHOOTFIN.NS"),
    ("NAUKRI", "Info Edge (Naukri.com)", "NAUKRI.NS"),
    ("NMDC", "NMDC", "NMDC.NS"),
    ("IDFCFIRSTB", "IDFC First Bank", "IDFCFIRSTB.NS"),
    ("PFC", "Power Finance Corporation", "PFC.NS"),
    ("PIDILITIND", "Pidilite Industries", "PIDILITIND.NS"),
    ("PNB", "Punjab National Bank", "PNB.NS"),
    ("RECLTD", "REC", "RECLTD.NS"),
    ("SAIL", "Steel Authority of India", "SAIL.NS"),
    ("SBICARD", "SBI Cards & Payment Services", "SBICARD.NS"),
    ("SIEMENS", "Siemens", "SIEMENS.NS"),
    ("SRF", "SRF", "SRF.NS"),
    ("TATAPOWER", "Tata Power", "TATAPOWER.NS"),
    ("TORNTPHARM", "Torrent Pharmaceuticals", "TORNTPHARM.NS"),
    ("TVSMOTOR", "TVS Motor", "TVSMOTOR.NS"),
    ("VEDL", "Vedanta", "VEDL.NS"),
    ("ETERNAL", "Eternal (formerly Zomato)", "ETERNAL.NS"),
    ("ZYDUSLIFE", "Zydus Lifesciences", "ZYDUSLIFE.NS"),
    ("POLYCAB", "Polycab India", "POLYCAB.NS"),
    ("ABCAPITAL", "Aditya Birla Capital", "ABCAPITAL.NS"),
    ("IRFC", "Indian Railway Finance Corporation", "IRFC.NS"),
    ("LODHA", "Macrotech Developers (Lodha)", "LODHA.NS"),
    ("PIIND", "PI Industries", "PIIND.NS"),
]
